# name
name: cd

# trigger
on:
  push:
    branches: [main]


#jobs to run
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"
      
      - name: Build the app
        run: ./scripts/buildprod.sh
